name: todo-app
services:
  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8000:80
    depends_on:
      - backend
      - frontend

  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./mongodb:/data/db
      - ./backup:/backup
    environment:
      - MONGO_INITDB_ROOT_USERNAME=farm
      - MONGO_INITDB_ROOT_PASSWORD=farmstack

  
  backup:
    image: mongo
    depends_on:
      - mongodb
    volumes:
      - ./backup:/backup
      - ./mongodb:/data/db
    entrypoint: ["bash", "-c", "while true; do /backup/backup_mongo.sh; sleep 86400; done"]

  frontend:
    image: "node:22"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
      - WDS_SOCKET_PORT=0
    volumes:
      - ./frontend/:/home/node/app
    expose:
      - "3000"
    ports:
      - "3000:3000"
    command: "npm run dev"
    
  backend:
    image: todo-app/backend
    build: ./backend
    volumes:
      - ./backend/:/usr/src/app
    expose:
      - "3001"
    ports:
      - "8001:3001"
    command: "python src/server.py"
    environment:
      - DEBUG=true
    env_file:
      - path: ./.env
        required: true